#
# To use this configuration:
#   ec validate image ... --policy github.com/enterprise-contract//configs/default
#
description: >
  Use the policy rules from the "minimal" collection. This and other collections are defined in
  https://enterprisecontract.dev/docs/ec-policies/release_policy.html#_available_rule_collections

publicKey: "k8s://tekton-chains/public-key"

sources:
  - name: Default
    policy:
      - github.com/enterprise-contract/ec-policies//policy/lib
      - github.com/enterprise-contract/ec-policies//policy/release
    data:
      - github.com/enterprise-contract/ec-policies//data

configuration:
  include:
    - "@minimal"
  exclude:
    # This can be removed once https://issues.redhat.com/browse/OCPBUGS-8428 is addressed
    - step_image_registries
