apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{"argocd.argoproj.io/sync-options":"SkipDryRunOnMissingResource=true"},"labels":{"app.kubernetes.io/instance":"build"},"name":"run-component-build","namespace":"jvm-build-service"},"spec":{"params":[{"name":"url","type":"string"},{"default":"","name":"context","type":"string"},{"name":"tag","type":"string"}],"results":[{"description":"The GAVs of any community artifacts that ended up in the output","name":"contaminants","value":"$(tasks.maven-run.results.contaminants)"}],"tasks":[{"name":"fetch-repository","params":[{"name":"url","value":"$(params.url)"},{"name":"subdirectory","value":""},{"name":"deleteExisting","value":"true"},{"name":"revision","value":"$(params.tag)"}],"taskRef":{"name":"git-clone"},"workspaces":[{"name":"output","workspace":"shared-workspace"}]},{"name":"maven-run","params":[{"name":"MAVEN_MIRROR_URL","value":"http://localhost:2000/maven2"},{"name":"CONTEXT_DIR","value":"$(params.context)"},{"name":"GOALS","value":["-DskipTests","clean","install","-Denforcer.skip"]}],"runAfter":["fetch-repository"],"taskRef":{"name":"run-maven-component-build"},"workspaces":[{"name":"maven-settings","workspace":"maven-settings"},{"name":"source","workspace":"shared-workspace"}]}],"workspaces":[{"name":"shared-workspace"},{"name":"maven-settings"}]}}
  creationTimestamp: "2022-05-25T09:45:35Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: build
  name: run-component-build
  namespace: jvm-build-service
  resourceVersion: "1466226"
  uid: 12c24f39-1a0a-48f4-9a6b-f9e61844dc57
spec:
  params:
  - name: url
    type: string
  - default: ""
    name: context
    type: string
  - name: tag
    type: string
  results:
  - description: The GAVs of any community artifacts that ended up in the output
    name: contaminants
    value: $(tasks.maven-run.results.contaminants)
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: $(params.url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.tag)
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: maven-run
    params:
    - name: MAVEN_MIRROR_URL
      value: http://localhost:2000/maven2
    - name: CONTEXT_DIR
      value: $(params.context)
    - name: GOALS
      value:
      - -DskipTests
      - clean
      - install
      - -Denforcer.skip
    runAfter:
    - fetch-repository
    taskRef:
      kind: Task
      name: run-maven-component-build
    workspaces:
    - name: maven-settings
      workspace: maven-settings
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace
  - name: maven-settings
